// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package graph

import (
	"github.com/gotha/niuniu-cms/data"
	"sync"
)

// Ensure, that attachmentServiceMock does implement attachmentService.
// If this is not the case, regenerate this file with moq.
var _ attachmentService = &attachmentServiceMock{}

// attachmentServiceMock is a mock implementation of attachmentService.
//
// 	func TestSomethingThatUsesattachmentService(t *testing.T) {
//
// 		// make and configure a mocked attachmentService
// 		mockedattachmentService := &attachmentServiceMock{
// 			DeleteFunc: func(id string) error {
// 				panic("mock out the Delete method")
// 			},
// 			GetFunc: func(id string) (*data.Attachment, error) {
// 				panic("mock out the Get method")
// 			},
// 			GetMultipleFunc: func(ids []string) ([]data.Attachment, error) {
// 				panic("mock out the GetMultiple method")
// 			},
// 			NewFunc: func(url string, title *string) (*data.Attachment, error) {
// 				panic("mock out the New method")
// 			},
// 			UpdateFunc: func(id string, url string, title *string) (*data.Attachment, error) {
// 				panic("mock out the Update method")
// 			},
// 		}
//
// 		// use mockedattachmentService in code that requires attachmentService
// 		// and then make assertions.
//
// 	}
type attachmentServiceMock struct {
	// DeleteFunc mocks the Delete method.
	DeleteFunc func(id string) error

	// GetFunc mocks the Get method.
	GetFunc func(id string) (*data.Attachment, error)

	// GetMultipleFunc mocks the GetMultiple method.
	GetMultipleFunc func(ids []string) ([]data.Attachment, error)

	// NewFunc mocks the New method.
	NewFunc func(url string, title *string) (*data.Attachment, error)

	// UpdateFunc mocks the Update method.
	UpdateFunc func(id string, url string, title *string) (*data.Attachment, error)

	// calls tracks calls to the methods.
	calls struct {
		// Delete holds details about calls to the Delete method.
		Delete []struct {
			// ID is the id argument value.
			ID string
		}
		// Get holds details about calls to the Get method.
		Get []struct {
			// ID is the id argument value.
			ID string
		}
		// GetMultiple holds details about calls to the GetMultiple method.
		GetMultiple []struct {
			// Ids is the ids argument value.
			Ids []string
		}
		// New holds details about calls to the New method.
		New []struct {
			// URL is the url argument value.
			URL string
			// Title is the title argument value.
			Title *string
		}
		// Update holds details about calls to the Update method.
		Update []struct {
			// ID is the id argument value.
			ID string
			// URL is the url argument value.
			URL string
			// Title is the title argument value.
			Title *string
		}
	}
	lockDelete      sync.RWMutex
	lockGet         sync.RWMutex
	lockGetMultiple sync.RWMutex
	lockNew         sync.RWMutex
	lockUpdate      sync.RWMutex
}

// Delete calls DeleteFunc.
func (mock *attachmentServiceMock) Delete(id string) error {
	if mock.DeleteFunc == nil {
		panic("attachmentServiceMock.DeleteFunc: method is nil but attachmentService.Delete was just called")
	}
	callInfo := struct {
		ID string
	}{
		ID: id,
	}
	mock.lockDelete.Lock()
	mock.calls.Delete = append(mock.calls.Delete, callInfo)
	mock.lockDelete.Unlock()
	return mock.DeleteFunc(id)
}

// DeleteCalls gets all the calls that were made to Delete.
// Check the length with:
//     len(mockedattachmentService.DeleteCalls())
func (mock *attachmentServiceMock) DeleteCalls() []struct {
	ID string
} {
	var calls []struct {
		ID string
	}
	mock.lockDelete.RLock()
	calls = mock.calls.Delete
	mock.lockDelete.RUnlock()
	return calls
}

// Get calls GetFunc.
func (mock *attachmentServiceMock) Get(id string) (*data.Attachment, error) {
	if mock.GetFunc == nil {
		panic("attachmentServiceMock.GetFunc: method is nil but attachmentService.Get was just called")
	}
	callInfo := struct {
		ID string
	}{
		ID: id,
	}
	mock.lockGet.Lock()
	mock.calls.Get = append(mock.calls.Get, callInfo)
	mock.lockGet.Unlock()
	return mock.GetFunc(id)
}

// GetCalls gets all the calls that were made to Get.
// Check the length with:
//     len(mockedattachmentService.GetCalls())
func (mock *attachmentServiceMock) GetCalls() []struct {
	ID string
} {
	var calls []struct {
		ID string
	}
	mock.lockGet.RLock()
	calls = mock.calls.Get
	mock.lockGet.RUnlock()
	return calls
}

// GetMultiple calls GetMultipleFunc.
func (mock *attachmentServiceMock) GetMultiple(ids []string) ([]data.Attachment, error) {
	if mock.GetMultipleFunc == nil {
		panic("attachmentServiceMock.GetMultipleFunc: method is nil but attachmentService.GetMultiple was just called")
	}
	callInfo := struct {
		Ids []string
	}{
		Ids: ids,
	}
	mock.lockGetMultiple.Lock()
	mock.calls.GetMultiple = append(mock.calls.GetMultiple, callInfo)
	mock.lockGetMultiple.Unlock()
	return mock.GetMultipleFunc(ids)
}

// GetMultipleCalls gets all the calls that were made to GetMultiple.
// Check the length with:
//     len(mockedattachmentService.GetMultipleCalls())
func (mock *attachmentServiceMock) GetMultipleCalls() []struct {
	Ids []string
} {
	var calls []struct {
		Ids []string
	}
	mock.lockGetMultiple.RLock()
	calls = mock.calls.GetMultiple
	mock.lockGetMultiple.RUnlock()
	return calls
}

// New calls NewFunc.
func (mock *attachmentServiceMock) New(url string, title *string) (*data.Attachment, error) {
	if mock.NewFunc == nil {
		panic("attachmentServiceMock.NewFunc: method is nil but attachmentService.New was just called")
	}
	callInfo := struct {
		URL   string
		Title *string
	}{
		URL:   url,
		Title: title,
	}
	mock.lockNew.Lock()
	mock.calls.New = append(mock.calls.New, callInfo)
	mock.lockNew.Unlock()
	return mock.NewFunc(url, title)
}

// NewCalls gets all the calls that were made to New.
// Check the length with:
//     len(mockedattachmentService.NewCalls())
func (mock *attachmentServiceMock) NewCalls() []struct {
	URL   string
	Title *string
} {
	var calls []struct {
		URL   string
		Title *string
	}
	mock.lockNew.RLock()
	calls = mock.calls.New
	mock.lockNew.RUnlock()
	return calls
}

// Update calls UpdateFunc.
func (mock *attachmentServiceMock) Update(id string, url string, title *string) (*data.Attachment, error) {
	if mock.UpdateFunc == nil {
		panic("attachmentServiceMock.UpdateFunc: method is nil but attachmentService.Update was just called")
	}
	callInfo := struct {
		ID    string
		URL   string
		Title *string
	}{
		ID:    id,
		URL:   url,
		Title: title,
	}
	mock.lockUpdate.Lock()
	mock.calls.Update = append(mock.calls.Update, callInfo)
	mock.lockUpdate.Unlock()
	return mock.UpdateFunc(id, url, title)
}

// UpdateCalls gets all the calls that were made to Update.
// Check the length with:
//     len(mockedattachmentService.UpdateCalls())
func (mock *attachmentServiceMock) UpdateCalls() []struct {
	ID    string
	URL   string
	Title *string
} {
	var calls []struct {
		ID    string
		URL   string
		Title *string
	}
	mock.lockUpdate.RLock()
	calls = mock.calls.Update
	mock.lockUpdate.RUnlock()
	return calls
}
