// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package graph

import (
	"github.com/gotha/niuniu-cms/data"
	"sync"
)

// Ensure, that documentServiceMock does implement documentService.
// If this is not the case, regenerate this file with moq.
var _ documentService = &documentServiceMock{}

// documentServiceMock is a mock implementation of documentService.
//
// 	func TestSomethingThatUsesdocumentService(t *testing.T) {
//
// 		// make and configure a mocked documentService
// 		mockeddocumentService := &documentServiceMock{
// 			DeleteFunc: func(id string) error {
// 				panic("mock out the Delete method")
// 			},
// 			GetFunc: func(id string) (data.Document, error) {
// 				panic("mock out the Get method")
// 			},
// 			GetAllFunc: func(limit *int, offset *int, sortBy *string, sortDesc *bool) ([]data.Document, error) {
// 				panic("mock out the GetAll method")
// 			},
// 			GetAllByTagFunc: func(tagIDs []string, limit *int, offset *int, sortBy *string, sortDesc *bool) ([]data.Document, error) {
// 				panic("mock out the GetAllByTag method")
// 			},
// 			GetNumDocumentsFunc: func() (int64, error) {
// 				panic("mock out the GetNumDocuments method")
// 			},
// 			GetNumDocumentsWithTagFunc: func(tagIDs []string) (int64, error) {
// 				panic("mock out the GetNumDocumentsWithTag method")
// 			},
// 			NewFunc: func(title string, body string, tags []data.Tag, attachments []data.Attachment) (*data.Document, error) {
// 				panic("mock out the New method")
// 			},
// 			UpdateFunc: func(id string, title *string, body *string, tags []data.Tag, attachments []data.Attachment) (*data.Document, error) {
// 				panic("mock out the Update method")
// 			},
// 		}
//
// 		// use mockeddocumentService in code that requires documentService
// 		// and then make assertions.
//
// 	}
type documentServiceMock struct {
	// DeleteFunc mocks the Delete method.
	DeleteFunc func(id string) error

	// GetFunc mocks the Get method.
	GetFunc func(id string) (data.Document, error)

	// GetAllFunc mocks the GetAll method.
	GetAllFunc func(limit *int, offset *int, sortBy *string, sortDesc *bool) ([]data.Document, error)

	// GetAllByTagFunc mocks the GetAllByTag method.
	GetAllByTagFunc func(tagIDs []string, limit *int, offset *int, sortBy *string, sortDesc *bool) ([]data.Document, error)

	// GetNumDocumentsFunc mocks the GetNumDocuments method.
	GetNumDocumentsFunc func() (int64, error)

	// GetNumDocumentsWithTagFunc mocks the GetNumDocumentsWithTag method.
	GetNumDocumentsWithTagFunc func(tagIDs []string) (int64, error)

	// NewFunc mocks the New method.
	NewFunc func(title string, body string, tags []data.Tag, attachments []data.Attachment) (*data.Document, error)

	// UpdateFunc mocks the Update method.
	UpdateFunc func(id string, title *string, body *string, tags []data.Tag, attachments []data.Attachment) (*data.Document, error)

	// calls tracks calls to the methods.
	calls struct {
		// Delete holds details about calls to the Delete method.
		Delete []struct {
			// ID is the id argument value.
			ID string
		}
		// Get holds details about calls to the Get method.
		Get []struct {
			// ID is the id argument value.
			ID string
		}
		// GetAll holds details about calls to the GetAll method.
		GetAll []struct {
			// Limit is the limit argument value.
			Limit *int
			// Offset is the offset argument value.
			Offset *int
			// SortBy is the sortBy argument value.
			SortBy *string
			// SortDesc is the sortDesc argument value.
			SortDesc *bool
		}
		// GetAllByTag holds details about calls to the GetAllByTag method.
		GetAllByTag []struct {
			// TagIDs is the tagIDs argument value.
			TagIDs []string
			// Limit is the limit argument value.
			Limit *int
			// Offset is the offset argument value.
			Offset *int
			// SortBy is the sortBy argument value.
			SortBy *string
			// SortDesc is the sortDesc argument value.
			SortDesc *bool
		}
		// GetNumDocuments holds details about calls to the GetNumDocuments method.
		GetNumDocuments []struct {
		}
		// GetNumDocumentsWithTag holds details about calls to the GetNumDocumentsWithTag method.
		GetNumDocumentsWithTag []struct {
			// TagIDs is the tagIDs argument value.
			TagIDs []string
		}
		// New holds details about calls to the New method.
		New []struct {
			// Title is the title argument value.
			Title string
			// Body is the body argument value.
			Body string
			// Tags is the tags argument value.
			Tags []data.Tag
			// Attachments is the attachments argument value.
			Attachments []data.Attachment
		}
		// Update holds details about calls to the Update method.
		Update []struct {
			// ID is the id argument value.
			ID string
			// Title is the title argument value.
			Title *string
			// Body is the body argument value.
			Body *string
			// Tags is the tags argument value.
			Tags []data.Tag
			// Attachments is the attachments argument value.
			Attachments []data.Attachment
		}
	}
	lockDelete                 sync.RWMutex
	lockGet                    sync.RWMutex
	lockGetAll                 sync.RWMutex
	lockGetAllByTag            sync.RWMutex
	lockGetNumDocuments        sync.RWMutex
	lockGetNumDocumentsWithTag sync.RWMutex
	lockNew                    sync.RWMutex
	lockUpdate                 sync.RWMutex
}

// Delete calls DeleteFunc.
func (mock *documentServiceMock) Delete(id string) error {
	if mock.DeleteFunc == nil {
		panic("documentServiceMock.DeleteFunc: method is nil but documentService.Delete was just called")
	}
	callInfo := struct {
		ID string
	}{
		ID: id,
	}
	mock.lockDelete.Lock()
	mock.calls.Delete = append(mock.calls.Delete, callInfo)
	mock.lockDelete.Unlock()
	return mock.DeleteFunc(id)
}

// DeleteCalls gets all the calls that were made to Delete.
// Check the length with:
//     len(mockeddocumentService.DeleteCalls())
func (mock *documentServiceMock) DeleteCalls() []struct {
	ID string
} {
	var calls []struct {
		ID string
	}
	mock.lockDelete.RLock()
	calls = mock.calls.Delete
	mock.lockDelete.RUnlock()
	return calls
}

// Get calls GetFunc.
func (mock *documentServiceMock) Get(id string) (data.Document, error) {
	if mock.GetFunc == nil {
		panic("documentServiceMock.GetFunc: method is nil but documentService.Get was just called")
	}
	callInfo := struct {
		ID string
	}{
		ID: id,
	}
	mock.lockGet.Lock()
	mock.calls.Get = append(mock.calls.Get, callInfo)
	mock.lockGet.Unlock()
	return mock.GetFunc(id)
}

// GetCalls gets all the calls that were made to Get.
// Check the length with:
//     len(mockeddocumentService.GetCalls())
func (mock *documentServiceMock) GetCalls() []struct {
	ID string
} {
	var calls []struct {
		ID string
	}
	mock.lockGet.RLock()
	calls = mock.calls.Get
	mock.lockGet.RUnlock()
	return calls
}

// GetAll calls GetAllFunc.
func (mock *documentServiceMock) GetAll(limit *int, offset *int, sortBy *string, sortDesc *bool) ([]data.Document, error) {
	if mock.GetAllFunc == nil {
		panic("documentServiceMock.GetAllFunc: method is nil but documentService.GetAll was just called")
	}
	callInfo := struct {
		Limit    *int
		Offset   *int
		SortBy   *string
		SortDesc *bool
	}{
		Limit:    limit,
		Offset:   offset,
		SortBy:   sortBy,
		SortDesc: sortDesc,
	}
	mock.lockGetAll.Lock()
	mock.calls.GetAll = append(mock.calls.GetAll, callInfo)
	mock.lockGetAll.Unlock()
	return mock.GetAllFunc(limit, offset, sortBy, sortDesc)
}

// GetAllCalls gets all the calls that were made to GetAll.
// Check the length with:
//     len(mockeddocumentService.GetAllCalls())
func (mock *documentServiceMock) GetAllCalls() []struct {
	Limit    *int
	Offset   *int
	SortBy   *string
	SortDesc *bool
} {
	var calls []struct {
		Limit    *int
		Offset   *int
		SortBy   *string
		SortDesc *bool
	}
	mock.lockGetAll.RLock()
	calls = mock.calls.GetAll
	mock.lockGetAll.RUnlock()
	return calls
}

// GetAllByTag calls GetAllByTagFunc.
func (mock *documentServiceMock) GetAllByTag(tagIDs []string, limit *int, offset *int, sortBy *string, sortDesc *bool) ([]data.Document, error) {
	if mock.GetAllByTagFunc == nil {
		panic("documentServiceMock.GetAllByTagFunc: method is nil but documentService.GetAllByTag was just called")
	}
	callInfo := struct {
		TagIDs   []string
		Limit    *int
		Offset   *int
		SortBy   *string
		SortDesc *bool
	}{
		TagIDs:   tagIDs,
		Limit:    limit,
		Offset:   offset,
		SortBy:   sortBy,
		SortDesc: sortDesc,
	}
	mock.lockGetAllByTag.Lock()
	mock.calls.GetAllByTag = append(mock.calls.GetAllByTag, callInfo)
	mock.lockGetAllByTag.Unlock()
	return mock.GetAllByTagFunc(tagIDs, limit, offset, sortBy, sortDesc)
}

// GetAllByTagCalls gets all the calls that were made to GetAllByTag.
// Check the length with:
//     len(mockeddocumentService.GetAllByTagCalls())
func (mock *documentServiceMock) GetAllByTagCalls() []struct {
	TagIDs   []string
	Limit    *int
	Offset   *int
	SortBy   *string
	SortDesc *bool
} {
	var calls []struct {
		TagIDs   []string
		Limit    *int
		Offset   *int
		SortBy   *string
		SortDesc *bool
	}
	mock.lockGetAllByTag.RLock()
	calls = mock.calls.GetAllByTag
	mock.lockGetAllByTag.RUnlock()
	return calls
}

// GetNumDocuments calls GetNumDocumentsFunc.
func (mock *documentServiceMock) GetNumDocuments() (int64, error) {
	if mock.GetNumDocumentsFunc == nil {
		panic("documentServiceMock.GetNumDocumentsFunc: method is nil but documentService.GetNumDocuments was just called")
	}
	callInfo := struct {
	}{}
	mock.lockGetNumDocuments.Lock()
	mock.calls.GetNumDocuments = append(mock.calls.GetNumDocuments, callInfo)
	mock.lockGetNumDocuments.Unlock()
	return mock.GetNumDocumentsFunc()
}

// GetNumDocumentsCalls gets all the calls that were made to GetNumDocuments.
// Check the length with:
//     len(mockeddocumentService.GetNumDocumentsCalls())
func (mock *documentServiceMock) GetNumDocumentsCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockGetNumDocuments.RLock()
	calls = mock.calls.GetNumDocuments
	mock.lockGetNumDocuments.RUnlock()
	return calls
}

// GetNumDocumentsWithTag calls GetNumDocumentsWithTagFunc.
func (mock *documentServiceMock) GetNumDocumentsWithTag(tagIDs []string) (int64, error) {
	if mock.GetNumDocumentsWithTagFunc == nil {
		panic("documentServiceMock.GetNumDocumentsWithTagFunc: method is nil but documentService.GetNumDocumentsWithTag was just called")
	}
	callInfo := struct {
		TagIDs []string
	}{
		TagIDs: tagIDs,
	}
	mock.lockGetNumDocumentsWithTag.Lock()
	mock.calls.GetNumDocumentsWithTag = append(mock.calls.GetNumDocumentsWithTag, callInfo)
	mock.lockGetNumDocumentsWithTag.Unlock()
	return mock.GetNumDocumentsWithTagFunc(tagIDs)
}

// GetNumDocumentsWithTagCalls gets all the calls that were made to GetNumDocumentsWithTag.
// Check the length with:
//     len(mockeddocumentService.GetNumDocumentsWithTagCalls())
func (mock *documentServiceMock) GetNumDocumentsWithTagCalls() []struct {
	TagIDs []string
} {
	var calls []struct {
		TagIDs []string
	}
	mock.lockGetNumDocumentsWithTag.RLock()
	calls = mock.calls.GetNumDocumentsWithTag
	mock.lockGetNumDocumentsWithTag.RUnlock()
	return calls
}

// New calls NewFunc.
func (mock *documentServiceMock) New(title string, body string, tags []data.Tag, attachments []data.Attachment) (*data.Document, error) {
	if mock.NewFunc == nil {
		panic("documentServiceMock.NewFunc: method is nil but documentService.New was just called")
	}
	callInfo := struct {
		Title       string
		Body        string
		Tags        []data.Tag
		Attachments []data.Attachment
	}{
		Title:       title,
		Body:        body,
		Tags:        tags,
		Attachments: attachments,
	}
	mock.lockNew.Lock()
	mock.calls.New = append(mock.calls.New, callInfo)
	mock.lockNew.Unlock()
	return mock.NewFunc(title, body, tags, attachments)
}

// NewCalls gets all the calls that were made to New.
// Check the length with:
//     len(mockeddocumentService.NewCalls())
func (mock *documentServiceMock) NewCalls() []struct {
	Title       string
	Body        string
	Tags        []data.Tag
	Attachments []data.Attachment
} {
	var calls []struct {
		Title       string
		Body        string
		Tags        []data.Tag
		Attachments []data.Attachment
	}
	mock.lockNew.RLock()
	calls = mock.calls.New
	mock.lockNew.RUnlock()
	return calls
}

// Update calls UpdateFunc.
func (mock *documentServiceMock) Update(id string, title *string, body *string, tags []data.Tag, attachments []data.Attachment) (*data.Document, error) {
	if mock.UpdateFunc == nil {
		panic("documentServiceMock.UpdateFunc: method is nil but documentService.Update was just called")
	}
	callInfo := struct {
		ID          string
		Title       *string
		Body        *string
		Tags        []data.Tag
		Attachments []data.Attachment
	}{
		ID:          id,
		Title:       title,
		Body:        body,
		Tags:        tags,
		Attachments: attachments,
	}
	mock.lockUpdate.Lock()
	mock.calls.Update = append(mock.calls.Update, callInfo)
	mock.lockUpdate.Unlock()
	return mock.UpdateFunc(id, title, body, tags, attachments)
}

// UpdateCalls gets all the calls that were made to Update.
// Check the length with:
//     len(mockeddocumentService.UpdateCalls())
func (mock *documentServiceMock) UpdateCalls() []struct {
	ID          string
	Title       *string
	Body        *string
	Tags        []data.Tag
	Attachments []data.Attachment
} {
	var calls []struct {
		ID          string
		Title       *string
		Body        *string
		Tags        []data.Tag
		Attachments []data.Attachment
	}
	mock.lockUpdate.RLock()
	calls = mock.calls.Update
	mock.lockUpdate.RUnlock()
	return calls
}
