// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package graph

import (
	"github.com/gotha/niuniu-cms/data"
	"sync"
)

// Ensure, that tagServiceMock does implement tagService.
// If this is not the case, regenerate this file with moq.
var _ tagService = &tagServiceMock{}

// tagServiceMock is a mock implementation of tagService.
//
// 	func TestSomethingThatUsestagService(t *testing.T) {
//
// 		// make and configure a mocked tagService
// 		mockedtagService := &tagServiceMock{
// 			DeleteFunc: func(id string) error {
// 				panic("mock out the Delete method")
// 			},
// 			GetFunc: func(id string) (*data.Tag, error) {
// 				panic("mock out the Get method")
// 			},
// 			GetAllFunc: func() ([]data.Tag, error) {
// 				panic("mock out the GetAll method")
// 			},
// 			GetMultipleFunc: func(ids []string) ([]data.Tag, error) {
// 				panic("mock out the GetMultiple method")
// 			},
// 			NewFunc: func(title string) (*data.Tag, error) {
// 				panic("mock out the New method")
// 			},
// 			UpdateFunc: func(id string, title string) (*data.Tag, error) {
// 				panic("mock out the Update method")
// 			},
// 		}
//
// 		// use mockedtagService in code that requires tagService
// 		// and then make assertions.
//
// 	}
type tagServiceMock struct {
	// DeleteFunc mocks the Delete method.
	DeleteFunc func(id string) error

	// GetFunc mocks the Get method.
	GetFunc func(id string) (*data.Tag, error)

	// GetAllFunc mocks the GetAll method.
	GetAllFunc func() ([]data.Tag, error)

	// GetMultipleFunc mocks the GetMultiple method.
	GetMultipleFunc func(ids []string) ([]data.Tag, error)

	// NewFunc mocks the New method.
	NewFunc func(title string) (*data.Tag, error)

	// UpdateFunc mocks the Update method.
	UpdateFunc func(id string, title string) (*data.Tag, error)

	// calls tracks calls to the methods.
	calls struct {
		// Delete holds details about calls to the Delete method.
		Delete []struct {
			// ID is the id argument value.
			ID string
		}
		// Get holds details about calls to the Get method.
		Get []struct {
			// ID is the id argument value.
			ID string
		}
		// GetAll holds details about calls to the GetAll method.
		GetAll []struct {
		}
		// GetMultiple holds details about calls to the GetMultiple method.
		GetMultiple []struct {
			// Ids is the ids argument value.
			Ids []string
		}
		// New holds details about calls to the New method.
		New []struct {
			// Title is the title argument value.
			Title string
		}
		// Update holds details about calls to the Update method.
		Update []struct {
			// ID is the id argument value.
			ID string
			// Title is the title argument value.
			Title string
		}
	}
	lockDelete      sync.RWMutex
	lockGet         sync.RWMutex
	lockGetAll      sync.RWMutex
	lockGetMultiple sync.RWMutex
	lockNew         sync.RWMutex
	lockUpdate      sync.RWMutex
}

// Delete calls DeleteFunc.
func (mock *tagServiceMock) Delete(id string) error {
	if mock.DeleteFunc == nil {
		panic("tagServiceMock.DeleteFunc: method is nil but tagService.Delete was just called")
	}
	callInfo := struct {
		ID string
	}{
		ID: id,
	}
	mock.lockDelete.Lock()
	mock.calls.Delete = append(mock.calls.Delete, callInfo)
	mock.lockDelete.Unlock()
	return mock.DeleteFunc(id)
}

// DeleteCalls gets all the calls that were made to Delete.
// Check the length with:
//     len(mockedtagService.DeleteCalls())
func (mock *tagServiceMock) DeleteCalls() []struct {
	ID string
} {
	var calls []struct {
		ID string
	}
	mock.lockDelete.RLock()
	calls = mock.calls.Delete
	mock.lockDelete.RUnlock()
	return calls
}

// Get calls GetFunc.
func (mock *tagServiceMock) Get(id string) (*data.Tag, error) {
	if mock.GetFunc == nil {
		panic("tagServiceMock.GetFunc: method is nil but tagService.Get was just called")
	}
	callInfo := struct {
		ID string
	}{
		ID: id,
	}
	mock.lockGet.Lock()
	mock.calls.Get = append(mock.calls.Get, callInfo)
	mock.lockGet.Unlock()
	return mock.GetFunc(id)
}

// GetCalls gets all the calls that were made to Get.
// Check the length with:
//     len(mockedtagService.GetCalls())
func (mock *tagServiceMock) GetCalls() []struct {
	ID string
} {
	var calls []struct {
		ID string
	}
	mock.lockGet.RLock()
	calls = mock.calls.Get
	mock.lockGet.RUnlock()
	return calls
}

// GetAll calls GetAllFunc.
func (mock *tagServiceMock) GetAll() ([]data.Tag, error) {
	if mock.GetAllFunc == nil {
		panic("tagServiceMock.GetAllFunc: method is nil but tagService.GetAll was just called")
	}
	callInfo := struct {
	}{}
	mock.lockGetAll.Lock()
	mock.calls.GetAll = append(mock.calls.GetAll, callInfo)
	mock.lockGetAll.Unlock()
	return mock.GetAllFunc()
}

// GetAllCalls gets all the calls that were made to GetAll.
// Check the length with:
//     len(mockedtagService.GetAllCalls())
func (mock *tagServiceMock) GetAllCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockGetAll.RLock()
	calls = mock.calls.GetAll
	mock.lockGetAll.RUnlock()
	return calls
}

// GetMultiple calls GetMultipleFunc.
func (mock *tagServiceMock) GetMultiple(ids []string) ([]data.Tag, error) {
	if mock.GetMultipleFunc == nil {
		panic("tagServiceMock.GetMultipleFunc: method is nil but tagService.GetMultiple was just called")
	}
	callInfo := struct {
		Ids []string
	}{
		Ids: ids,
	}
	mock.lockGetMultiple.Lock()
	mock.calls.GetMultiple = append(mock.calls.GetMultiple, callInfo)
	mock.lockGetMultiple.Unlock()
	return mock.GetMultipleFunc(ids)
}

// GetMultipleCalls gets all the calls that were made to GetMultiple.
// Check the length with:
//     len(mockedtagService.GetMultipleCalls())
func (mock *tagServiceMock) GetMultipleCalls() []struct {
	Ids []string
} {
	var calls []struct {
		Ids []string
	}
	mock.lockGetMultiple.RLock()
	calls = mock.calls.GetMultiple
	mock.lockGetMultiple.RUnlock()
	return calls
}

// New calls NewFunc.
func (mock *tagServiceMock) New(title string) (*data.Tag, error) {
	if mock.NewFunc == nil {
		panic("tagServiceMock.NewFunc: method is nil but tagService.New was just called")
	}
	callInfo := struct {
		Title string
	}{
		Title: title,
	}
	mock.lockNew.Lock()
	mock.calls.New = append(mock.calls.New, callInfo)
	mock.lockNew.Unlock()
	return mock.NewFunc(title)
}

// NewCalls gets all the calls that were made to New.
// Check the length with:
//     len(mockedtagService.NewCalls())
func (mock *tagServiceMock) NewCalls() []struct {
	Title string
} {
	var calls []struct {
		Title string
	}
	mock.lockNew.RLock()
	calls = mock.calls.New
	mock.lockNew.RUnlock()
	return calls
}

// Update calls UpdateFunc.
func (mock *tagServiceMock) Update(id string, title string) (*data.Tag, error) {
	if mock.UpdateFunc == nil {
		panic("tagServiceMock.UpdateFunc: method is nil but tagService.Update was just called")
	}
	callInfo := struct {
		ID    string
		Title string
	}{
		ID:    id,
		Title: title,
	}
	mock.lockUpdate.Lock()
	mock.calls.Update = append(mock.calls.Update, callInfo)
	mock.lockUpdate.Unlock()
	return mock.UpdateFunc(id, title)
}

// UpdateCalls gets all the calls that were made to Update.
// Check the length with:
//     len(mockedtagService.UpdateCalls())
func (mock *tagServiceMock) UpdateCalls() []struct {
	ID    string
	Title string
} {
	var calls []struct {
		ID    string
		Title string
	}
	mock.lockUpdate.RLock()
	calls = mock.calls.Update
	mock.lockUpdate.RUnlock()
	return calls
}
