// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Document struct {
	ID        string `json:"id"`
	Title     string `json:"title"`
	Body      string `json:"body"`
	CreatedAt string `json:"createdAt"`
	UpdatedAt string `json:"updatedAt"`
	Tags      []*Tag `json:"tags"`
}

type Documents struct {
	Documents []*Document `json:"documents"`
	Count     int         `json:"count"`
}

type NewDocument struct {
	Title string   `json:"title"`
	Body  string   `json:"body"`
	Tags  []string `json:"tags"`
}

type NewTag struct {
	Title string `json:"title"`
}

type Tag struct {
	ID        string `json:"id"`
	Title     string `json:"title"`
	CreatedAt string `json:"createdAt"`
	UpdatedAt string `json:"updatedAt"`
}

type UpdateDocument struct {
	Title *string  `json:"title"`
	Body  *string  `json:"body"`
	Tags  []string `json:"tags"`
}

type UpdateTag struct {
	Title string `json:"title"`
}
