// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Document struct {
	ID    string `json:"id"`
	Title string `json:"title"`
	Body  string `json:"body"`
	Tags  []*Tag `json:"tags"`
}

type NewDocument struct {
	Title string   `json:"title"`
	Body  string   `json:"body"`
	Tags  []string `json:"tags"`
}

type NewTag struct {
	Title string `json:"title"`
}

type Tag struct {
	ID    string `json:"id"`
	Title string `json:"title"`
}

type UpdateDocument struct {
	Title string `json:"title"`
	Body  string `json:"body"`
}

type UpdateTag struct {
	Title string `json:"title"`
}
