// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Attachment struct {
	ID        string  `json:"id"`
	Title     *string `json:"title"`
	URL       string  `json:"url"`
	CreatedAt string  `json:"createdAt"`
	UpdatedAt string  `json:"updatedAt"`
}

type Document struct {
	ID          string        `json:"id"`
	Title       string        `json:"title"`
	Body        string        `json:"body"`
	CreatedAt   string        `json:"createdAt"`
	UpdatedAt   string        `json:"updatedAt"`
	Tags        []*Tag        `json:"tags"`
	Attachments []*Attachment `json:"attachments"`
}

type Documents struct {
	Documents []*Document `json:"documents"`
	Count     int         `json:"count"`
}

type NewAttachment struct {
	Title *string `json:"title"`
	URL   string  `json:"url"`
}

type NewDocument struct {
	Title       string   `json:"title"`
	Body        string   `json:"body"`
	Tags        []string `json:"tags"`
	Attachments []string `json:"attachments"`
}

type NewTag struct {
	Title string `json:"title"`
}

type Tag struct {
	ID        string `json:"id"`
	Title     string `json:"title"`
	CreatedAt string `json:"createdAt"`
	UpdatedAt string `json:"updatedAt"`
}

type UpdateAttachment struct {
	Title *string `json:"title"`
	URL   string  `json:"url"`
}

type UpdateDocument struct {
	Title       *string  `json:"title"`
	Body        *string  `json:"body"`
	Tags        []string `json:"tags"`
	Attachments []string `json:"attachments"`
}

type UpdateTag struct {
	Title string `json:"title"`
}
