// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package document

import (
	"github.com/gotha/niuniu-cms/db"
	"sync"
)

// Ensure, that repositoryMock does implement repository.
// If this is not the case, regenerate this file with moq.
var _ repository = &repositoryMock{}

// repositoryMock is a mock implementation of repository.
//
// 	func TestSomethingThatUsesrepository(t *testing.T) {
//
// 		// make and configure a mocked repository
// 		mockedrepository := &repositoryMock{
// 			CreateFunc: func(title string, body string, tags []db.Tag) (*db.Document, error) {
// 				panic("mock out the Create method")
// 			},
// 			DeleteFunc: func(id string) error {
// 				panic("mock out the Delete method")
// 			},
// 			GetFunc: func(id string) (*db.Document, error) {
// 				panic("mock out the Get method")
// 			},
// 			GetAllFunc: func(limit *int, offset *int, sortBy *string, sortDesc *bool) ([]db.Document, error) {
// 				panic("mock out the GetAll method")
// 			},
// 			GetAllByTagFunc: func(tagIDs []string, limit *int, offset *int, sortBy *string, sortDesc *bool) ([]db.Document, error) {
// 				panic("mock out the GetAllByTag method")
// 			},
// 			GetNumDocumentsFunc: func() (int64, error) {
// 				panic("mock out the GetNumDocuments method")
// 			},
// 			GetNumDocumentsWithTagFunc: func(tagIDs []string) (int64, error) {
// 				panic("mock out the GetNumDocumentsWithTag method")
// 			},
// 			UpdateFunc: func(doc *db.Document) (*db.Document, error) {
// 				panic("mock out the Update method")
// 			},
// 		}
//
// 		// use mockedrepository in code that requires repository
// 		// and then make assertions.
//
// 	}
type repositoryMock struct {
	// CreateFunc mocks the Create method.
	CreateFunc func(title string, body string, tags []db.Tag) (*db.Document, error)

	// DeleteFunc mocks the Delete method.
	DeleteFunc func(id string) error

	// GetFunc mocks the Get method.
	GetFunc func(id string) (*db.Document, error)

	// GetAllFunc mocks the GetAll method.
	GetAllFunc func(limit *int, offset *int, sortBy *string, sortDesc *bool) ([]db.Document, error)

	// GetAllByTagFunc mocks the GetAllByTag method.
	GetAllByTagFunc func(tagIDs []string, limit *int, offset *int, sortBy *string, sortDesc *bool) ([]db.Document, error)

	// GetNumDocumentsFunc mocks the GetNumDocuments method.
	GetNumDocumentsFunc func() (int64, error)

	// GetNumDocumentsWithTagFunc mocks the GetNumDocumentsWithTag method.
	GetNumDocumentsWithTagFunc func(tagIDs []string) (int64, error)

	// UpdateFunc mocks the Update method.
	UpdateFunc func(doc *db.Document) (*db.Document, error)

	// calls tracks calls to the methods.
	calls struct {
		// Create holds details about calls to the Create method.
		Create []struct {
			// Title is the title argument value.
			Title string
			// Body is the body argument value.
			Body string
			// Tags is the tags argument value.
			Tags []db.Tag
		}
		// Delete holds details about calls to the Delete method.
		Delete []struct {
			// ID is the id argument value.
			ID string
		}
		// Get holds details about calls to the Get method.
		Get []struct {
			// ID is the id argument value.
			ID string
		}
		// GetAll holds details about calls to the GetAll method.
		GetAll []struct {
			// Limit is the limit argument value.
			Limit *int
			// Offset is the offset argument value.
			Offset *int
			// SortBy is the sortBy argument value.
			SortBy *string
			// SortDesc is the sortDesc argument value.
			SortDesc *bool
		}
		// GetAllByTag holds details about calls to the GetAllByTag method.
		GetAllByTag []struct {
			// TagIDs is the tagIDs argument value.
			TagIDs []string
			// Limit is the limit argument value.
			Limit *int
			// Offset is the offset argument value.
			Offset *int
			// SortBy is the sortBy argument value.
			SortBy *string
			// SortDesc is the sortDesc argument value.
			SortDesc *bool
		}
		// GetNumDocuments holds details about calls to the GetNumDocuments method.
		GetNumDocuments []struct {
		}
		// GetNumDocumentsWithTag holds details about calls to the GetNumDocumentsWithTag method.
		GetNumDocumentsWithTag []struct {
			// TagIDs is the tagIDs argument value.
			TagIDs []string
		}
		// Update holds details about calls to the Update method.
		Update []struct {
			// Doc is the doc argument value.
			Doc *db.Document
		}
	}
	lockCreate                 sync.RWMutex
	lockDelete                 sync.RWMutex
	lockGet                    sync.RWMutex
	lockGetAll                 sync.RWMutex
	lockGetAllByTag            sync.RWMutex
	lockGetNumDocuments        sync.RWMutex
	lockGetNumDocumentsWithTag sync.RWMutex
	lockUpdate                 sync.RWMutex
}

// Create calls CreateFunc.
func (mock *repositoryMock) Create(title string, body string, tags []db.Tag) (*db.Document, error) {
	if mock.CreateFunc == nil {
		panic("repositoryMock.CreateFunc: method is nil but repository.Create was just called")
	}
	callInfo := struct {
		Title string
		Body  string
		Tags  []db.Tag
	}{
		Title: title,
		Body:  body,
		Tags:  tags,
	}
	mock.lockCreate.Lock()
	mock.calls.Create = append(mock.calls.Create, callInfo)
	mock.lockCreate.Unlock()
	return mock.CreateFunc(title, body, tags)
}

// CreateCalls gets all the calls that were made to Create.
// Check the length with:
//     len(mockedrepository.CreateCalls())
func (mock *repositoryMock) CreateCalls() []struct {
	Title string
	Body  string
	Tags  []db.Tag
} {
	var calls []struct {
		Title string
		Body  string
		Tags  []db.Tag
	}
	mock.lockCreate.RLock()
	calls = mock.calls.Create
	mock.lockCreate.RUnlock()
	return calls
}

// Delete calls DeleteFunc.
func (mock *repositoryMock) Delete(id string) error {
	if mock.DeleteFunc == nil {
		panic("repositoryMock.DeleteFunc: method is nil but repository.Delete was just called")
	}
	callInfo := struct {
		ID string
	}{
		ID: id,
	}
	mock.lockDelete.Lock()
	mock.calls.Delete = append(mock.calls.Delete, callInfo)
	mock.lockDelete.Unlock()
	return mock.DeleteFunc(id)
}

// DeleteCalls gets all the calls that were made to Delete.
// Check the length with:
//     len(mockedrepository.DeleteCalls())
func (mock *repositoryMock) DeleteCalls() []struct {
	ID string
} {
	var calls []struct {
		ID string
	}
	mock.lockDelete.RLock()
	calls = mock.calls.Delete
	mock.lockDelete.RUnlock()
	return calls
}

// Get calls GetFunc.
func (mock *repositoryMock) Get(id string) (*db.Document, error) {
	if mock.GetFunc == nil {
		panic("repositoryMock.GetFunc: method is nil but repository.Get was just called")
	}
	callInfo := struct {
		ID string
	}{
		ID: id,
	}
	mock.lockGet.Lock()
	mock.calls.Get = append(mock.calls.Get, callInfo)
	mock.lockGet.Unlock()
	return mock.GetFunc(id)
}

// GetCalls gets all the calls that were made to Get.
// Check the length with:
//     len(mockedrepository.GetCalls())
func (mock *repositoryMock) GetCalls() []struct {
	ID string
} {
	var calls []struct {
		ID string
	}
	mock.lockGet.RLock()
	calls = mock.calls.Get
	mock.lockGet.RUnlock()
	return calls
}

// GetAll calls GetAllFunc.
func (mock *repositoryMock) GetAll(limit *int, offset *int, sortBy *string, sortDesc *bool) ([]db.Document, error) {
	if mock.GetAllFunc == nil {
		panic("repositoryMock.GetAllFunc: method is nil but repository.GetAll was just called")
	}
	callInfo := struct {
		Limit    *int
		Offset   *int
		SortBy   *string
		SortDesc *bool
	}{
		Limit:    limit,
		Offset:   offset,
		SortBy:   sortBy,
		SortDesc: sortDesc,
	}
	mock.lockGetAll.Lock()
	mock.calls.GetAll = append(mock.calls.GetAll, callInfo)
	mock.lockGetAll.Unlock()
	return mock.GetAllFunc(limit, offset, sortBy, sortDesc)
}

// GetAllCalls gets all the calls that were made to GetAll.
// Check the length with:
//     len(mockedrepository.GetAllCalls())
func (mock *repositoryMock) GetAllCalls() []struct {
	Limit    *int
	Offset   *int
	SortBy   *string
	SortDesc *bool
} {
	var calls []struct {
		Limit    *int
		Offset   *int
		SortBy   *string
		SortDesc *bool
	}
	mock.lockGetAll.RLock()
	calls = mock.calls.GetAll
	mock.lockGetAll.RUnlock()
	return calls
}

// GetAllByTag calls GetAllByTagFunc.
func (mock *repositoryMock) GetAllByTag(tagIDs []string, limit *int, offset *int, sortBy *string, sortDesc *bool) ([]db.Document, error) {
	if mock.GetAllByTagFunc == nil {
		panic("repositoryMock.GetAllByTagFunc: method is nil but repository.GetAllByTag was just called")
	}
	callInfo := struct {
		TagIDs   []string
		Limit    *int
		Offset   *int
		SortBy   *string
		SortDesc *bool
	}{
		TagIDs:   tagIDs,
		Limit:    limit,
		Offset:   offset,
		SortBy:   sortBy,
		SortDesc: sortDesc,
	}
	mock.lockGetAllByTag.Lock()
	mock.calls.GetAllByTag = append(mock.calls.GetAllByTag, callInfo)
	mock.lockGetAllByTag.Unlock()
	return mock.GetAllByTagFunc(tagIDs, limit, offset, sortBy, sortDesc)
}

// GetAllByTagCalls gets all the calls that were made to GetAllByTag.
// Check the length with:
//     len(mockedrepository.GetAllByTagCalls())
func (mock *repositoryMock) GetAllByTagCalls() []struct {
	TagIDs   []string
	Limit    *int
	Offset   *int
	SortBy   *string
	SortDesc *bool
} {
	var calls []struct {
		TagIDs   []string
		Limit    *int
		Offset   *int
		SortBy   *string
		SortDesc *bool
	}
	mock.lockGetAllByTag.RLock()
	calls = mock.calls.GetAllByTag
	mock.lockGetAllByTag.RUnlock()
	return calls
}

// GetNumDocuments calls GetNumDocumentsFunc.
func (mock *repositoryMock) GetNumDocuments() (int64, error) {
	if mock.GetNumDocumentsFunc == nil {
		panic("repositoryMock.GetNumDocumentsFunc: method is nil but repository.GetNumDocuments was just called")
	}
	callInfo := struct {
	}{}
	mock.lockGetNumDocuments.Lock()
	mock.calls.GetNumDocuments = append(mock.calls.GetNumDocuments, callInfo)
	mock.lockGetNumDocuments.Unlock()
	return mock.GetNumDocumentsFunc()
}

// GetNumDocumentsCalls gets all the calls that were made to GetNumDocuments.
// Check the length with:
//     len(mockedrepository.GetNumDocumentsCalls())
func (mock *repositoryMock) GetNumDocumentsCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockGetNumDocuments.RLock()
	calls = mock.calls.GetNumDocuments
	mock.lockGetNumDocuments.RUnlock()
	return calls
}

// GetNumDocumentsWithTag calls GetNumDocumentsWithTagFunc.
func (mock *repositoryMock) GetNumDocumentsWithTag(tagIDs []string) (int64, error) {
	if mock.GetNumDocumentsWithTagFunc == nil {
		panic("repositoryMock.GetNumDocumentsWithTagFunc: method is nil but repository.GetNumDocumentsWithTag was just called")
	}
	callInfo := struct {
		TagIDs []string
	}{
		TagIDs: tagIDs,
	}
	mock.lockGetNumDocumentsWithTag.Lock()
	mock.calls.GetNumDocumentsWithTag = append(mock.calls.GetNumDocumentsWithTag, callInfo)
	mock.lockGetNumDocumentsWithTag.Unlock()
	return mock.GetNumDocumentsWithTagFunc(tagIDs)
}

// GetNumDocumentsWithTagCalls gets all the calls that were made to GetNumDocumentsWithTag.
// Check the length with:
//     len(mockedrepository.GetNumDocumentsWithTagCalls())
func (mock *repositoryMock) GetNumDocumentsWithTagCalls() []struct {
	TagIDs []string
} {
	var calls []struct {
		TagIDs []string
	}
	mock.lockGetNumDocumentsWithTag.RLock()
	calls = mock.calls.GetNumDocumentsWithTag
	mock.lockGetNumDocumentsWithTag.RUnlock()
	return calls
}

// Update calls UpdateFunc.
func (mock *repositoryMock) Update(doc *db.Document) (*db.Document, error) {
	if mock.UpdateFunc == nil {
		panic("repositoryMock.UpdateFunc: method is nil but repository.Update was just called")
	}
	callInfo := struct {
		Doc *db.Document
	}{
		Doc: doc,
	}
	mock.lockUpdate.Lock()
	mock.calls.Update = append(mock.calls.Update, callInfo)
	mock.lockUpdate.Unlock()
	return mock.UpdateFunc(doc)
}

// UpdateCalls gets all the calls that were made to Update.
// Check the length with:
//     len(mockedrepository.UpdateCalls())
func (mock *repositoryMock) UpdateCalls() []struct {
	Doc *db.Document
} {
	var calls []struct {
		Doc *db.Document
	}
	mock.lockUpdate.RLock()
	calls = mock.calls.Update
	mock.lockUpdate.RUnlock()
	return calls
}
