// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package document

import (
	"github.com/gotha/niuniu-cms/db"
	"sync"
)

// Ensure, that tagServiceMock does implement tagService.
// If this is not the case, regenerate this file with moq.
var _ tagService = &tagServiceMock{}

// tagServiceMock is a mock implementation of tagService.
//
// 	func TestSomethingThatUsestagService(t *testing.T) {
//
// 		// make and configure a mocked tagService
// 		mockedtagService := &tagServiceMock{
// 			GetMultipleFunc: func(ids []string) ([]db.Tag, error) {
// 				panic("mock out the GetMultiple method")
// 			},
// 		}
//
// 		// use mockedtagService in code that requires tagService
// 		// and then make assertions.
//
// 	}
type tagServiceMock struct {
	// GetMultipleFunc mocks the GetMultiple method.
	GetMultipleFunc func(ids []string) ([]db.Tag, error)

	// calls tracks calls to the methods.
	calls struct {
		// GetMultiple holds details about calls to the GetMultiple method.
		GetMultiple []struct {
			// Ids is the ids argument value.
			Ids []string
		}
	}
	lockGetMultiple sync.RWMutex
}

// GetMultiple calls GetMultipleFunc.
func (mock *tagServiceMock) GetMultiple(ids []string) ([]db.Tag, error) {
	if mock.GetMultipleFunc == nil {
		panic("tagServiceMock.GetMultipleFunc: method is nil but tagService.GetMultiple was just called")
	}
	callInfo := struct {
		Ids []string
	}{
		Ids: ids,
	}
	mock.lockGetMultiple.Lock()
	mock.calls.GetMultiple = append(mock.calls.GetMultiple, callInfo)
	mock.lockGetMultiple.Unlock()
	return mock.GetMultipleFunc(ids)
}

// GetMultipleCalls gets all the calls that were made to GetMultiple.
// Check the length with:
//     len(mockedtagService.GetMultipleCalls())
func (mock *tagServiceMock) GetMultipleCalls() []struct {
	Ids []string
} {
	var calls []struct {
		Ids []string
	}
	mock.lockGetMultiple.RLock()
	calls = mock.calls.GetMultiple
	mock.lockGetMultiple.RUnlock()
	return calls
}
