// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package tag

import (
	"github.com/gotha/niuniu-cms/db"
	"sync"
)

// Ensure, that repositoryMock does implement repository.
// If this is not the case, regenerate this file with moq.
var _ repository = &repositoryMock{}

// repositoryMock is a mock implementation of repository.
//
// 	func TestSomethingThatUsesrepository(t *testing.T) {
//
// 		// make and configure a mocked repository
// 		mockedrepository := &repositoryMock{
// 			CreateFunc: func(title string) (*db.Tag, error) {
// 				panic("mock out the Create method")
// 			},
// 			DeleteFunc: func(id string) error {
// 				panic("mock out the Delete method")
// 			},
// 			GetFunc: func(id string) (*db.Tag, error) {
// 				panic("mock out the Get method")
// 			},
// 			GetAllFunc: func() ([]db.Tag, error) {
// 				panic("mock out the GetAll method")
// 			},
// 			GetMultipleFunc: func(ids []string) ([]db.Tag, error) {
// 				panic("mock out the GetMultiple method")
// 			},
// 			GetTagByTitleFunc: func(title string) (*db.Tag, error) {
// 				panic("mock out the GetTagByTitle method")
// 			},
// 			UpdateFunc: func(tag db.Tag, title string) (*db.Tag, error) {
// 				panic("mock out the Update method")
// 			},
// 		}
//
// 		// use mockedrepository in code that requires repository
// 		// and then make assertions.
//
// 	}
type repositoryMock struct {
	// CreateFunc mocks the Create method.
	CreateFunc func(title string) (*db.Tag, error)

	// DeleteFunc mocks the Delete method.
	DeleteFunc func(id string) error

	// GetFunc mocks the Get method.
	GetFunc func(id string) (*db.Tag, error)

	// GetAllFunc mocks the GetAll method.
	GetAllFunc func() ([]db.Tag, error)

	// GetMultipleFunc mocks the GetMultiple method.
	GetMultipleFunc func(ids []string) ([]db.Tag, error)

	// GetTagByTitleFunc mocks the GetTagByTitle method.
	GetTagByTitleFunc func(title string) (*db.Tag, error)

	// UpdateFunc mocks the Update method.
	UpdateFunc func(tag db.Tag, title string) (*db.Tag, error)

	// calls tracks calls to the methods.
	calls struct {
		// Create holds details about calls to the Create method.
		Create []struct {
			// Title is the title argument value.
			Title string
		}
		// Delete holds details about calls to the Delete method.
		Delete []struct {
			// ID is the id argument value.
			ID string
		}
		// Get holds details about calls to the Get method.
		Get []struct {
			// ID is the id argument value.
			ID string
		}
		// GetAll holds details about calls to the GetAll method.
		GetAll []struct {
		}
		// GetMultiple holds details about calls to the GetMultiple method.
		GetMultiple []struct {
			// Ids is the ids argument value.
			Ids []string
		}
		// GetTagByTitle holds details about calls to the GetTagByTitle method.
		GetTagByTitle []struct {
			// Title is the title argument value.
			Title string
		}
		// Update holds details about calls to the Update method.
		Update []struct {
			// Tag is the tag argument value.
			Tag db.Tag
			// Title is the title argument value.
			Title string
		}
	}
	lockCreate        sync.RWMutex
	lockDelete        sync.RWMutex
	lockGet           sync.RWMutex
	lockGetAll        sync.RWMutex
	lockGetMultiple   sync.RWMutex
	lockGetTagByTitle sync.RWMutex
	lockUpdate        sync.RWMutex
}

// Create calls CreateFunc.
func (mock *repositoryMock) Create(title string) (*db.Tag, error) {
	if mock.CreateFunc == nil {
		panic("repositoryMock.CreateFunc: method is nil but repository.Create was just called")
	}
	callInfo := struct {
		Title string
	}{
		Title: title,
	}
	mock.lockCreate.Lock()
	mock.calls.Create = append(mock.calls.Create, callInfo)
	mock.lockCreate.Unlock()
	return mock.CreateFunc(title)
}

// CreateCalls gets all the calls that were made to Create.
// Check the length with:
//     len(mockedrepository.CreateCalls())
func (mock *repositoryMock) CreateCalls() []struct {
	Title string
} {
	var calls []struct {
		Title string
	}
	mock.lockCreate.RLock()
	calls = mock.calls.Create
	mock.lockCreate.RUnlock()
	return calls
}

// Delete calls DeleteFunc.
func (mock *repositoryMock) Delete(id string) error {
	if mock.DeleteFunc == nil {
		panic("repositoryMock.DeleteFunc: method is nil but repository.Delete was just called")
	}
	callInfo := struct {
		ID string
	}{
		ID: id,
	}
	mock.lockDelete.Lock()
	mock.calls.Delete = append(mock.calls.Delete, callInfo)
	mock.lockDelete.Unlock()
	return mock.DeleteFunc(id)
}

// DeleteCalls gets all the calls that were made to Delete.
// Check the length with:
//     len(mockedrepository.DeleteCalls())
func (mock *repositoryMock) DeleteCalls() []struct {
	ID string
} {
	var calls []struct {
		ID string
	}
	mock.lockDelete.RLock()
	calls = mock.calls.Delete
	mock.lockDelete.RUnlock()
	return calls
}

// Get calls GetFunc.
func (mock *repositoryMock) Get(id string) (*db.Tag, error) {
	if mock.GetFunc == nil {
		panic("repositoryMock.GetFunc: method is nil but repository.Get was just called")
	}
	callInfo := struct {
		ID string
	}{
		ID: id,
	}
	mock.lockGet.Lock()
	mock.calls.Get = append(mock.calls.Get, callInfo)
	mock.lockGet.Unlock()
	return mock.GetFunc(id)
}

// GetCalls gets all the calls that were made to Get.
// Check the length with:
//     len(mockedrepository.GetCalls())
func (mock *repositoryMock) GetCalls() []struct {
	ID string
} {
	var calls []struct {
		ID string
	}
	mock.lockGet.RLock()
	calls = mock.calls.Get
	mock.lockGet.RUnlock()
	return calls
}

// GetAll calls GetAllFunc.
func (mock *repositoryMock) GetAll() ([]db.Tag, error) {
	if mock.GetAllFunc == nil {
		panic("repositoryMock.GetAllFunc: method is nil but repository.GetAll was just called")
	}
	callInfo := struct {
	}{}
	mock.lockGetAll.Lock()
	mock.calls.GetAll = append(mock.calls.GetAll, callInfo)
	mock.lockGetAll.Unlock()
	return mock.GetAllFunc()
}

// GetAllCalls gets all the calls that were made to GetAll.
// Check the length with:
//     len(mockedrepository.GetAllCalls())
func (mock *repositoryMock) GetAllCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockGetAll.RLock()
	calls = mock.calls.GetAll
	mock.lockGetAll.RUnlock()
	return calls
}

// GetMultiple calls GetMultipleFunc.
func (mock *repositoryMock) GetMultiple(ids []string) ([]db.Tag, error) {
	if mock.GetMultipleFunc == nil {
		panic("repositoryMock.GetMultipleFunc: method is nil but repository.GetMultiple was just called")
	}
	callInfo := struct {
		Ids []string
	}{
		Ids: ids,
	}
	mock.lockGetMultiple.Lock()
	mock.calls.GetMultiple = append(mock.calls.GetMultiple, callInfo)
	mock.lockGetMultiple.Unlock()
	return mock.GetMultipleFunc(ids)
}

// GetMultipleCalls gets all the calls that were made to GetMultiple.
// Check the length with:
//     len(mockedrepository.GetMultipleCalls())
func (mock *repositoryMock) GetMultipleCalls() []struct {
	Ids []string
} {
	var calls []struct {
		Ids []string
	}
	mock.lockGetMultiple.RLock()
	calls = mock.calls.GetMultiple
	mock.lockGetMultiple.RUnlock()
	return calls
}

// GetTagByTitle calls GetTagByTitleFunc.
func (mock *repositoryMock) GetTagByTitle(title string) (*db.Tag, error) {
	if mock.GetTagByTitleFunc == nil {
		panic("repositoryMock.GetTagByTitleFunc: method is nil but repository.GetTagByTitle was just called")
	}
	callInfo := struct {
		Title string
	}{
		Title: title,
	}
	mock.lockGetTagByTitle.Lock()
	mock.calls.GetTagByTitle = append(mock.calls.GetTagByTitle, callInfo)
	mock.lockGetTagByTitle.Unlock()
	return mock.GetTagByTitleFunc(title)
}

// GetTagByTitleCalls gets all the calls that were made to GetTagByTitle.
// Check the length with:
//     len(mockedrepository.GetTagByTitleCalls())
func (mock *repositoryMock) GetTagByTitleCalls() []struct {
	Title string
} {
	var calls []struct {
		Title string
	}
	mock.lockGetTagByTitle.RLock()
	calls = mock.calls.GetTagByTitle
	mock.lockGetTagByTitle.RUnlock()
	return calls
}

// Update calls UpdateFunc.
func (mock *repositoryMock) Update(tag db.Tag, title string) (*db.Tag, error) {
	if mock.UpdateFunc == nil {
		panic("repositoryMock.UpdateFunc: method is nil but repository.Update was just called")
	}
	callInfo := struct {
		Tag   db.Tag
		Title string
	}{
		Tag:   tag,
		Title: title,
	}
	mock.lockUpdate.Lock()
	mock.calls.Update = append(mock.calls.Update, callInfo)
	mock.lockUpdate.Unlock()
	return mock.UpdateFunc(tag, title)
}

// UpdateCalls gets all the calls that were made to Update.
// Check the length with:
//     len(mockedrepository.UpdateCalls())
func (mock *repositoryMock) UpdateCalls() []struct {
	Tag   db.Tag
	Title string
} {
	var calls []struct {
		Tag   db.Tag
		Title string
	}
	mock.lockUpdate.RLock()
	calls = mock.calls.Update
	mock.lockUpdate.RUnlock()
	return calls
}
